/**
 * Generates supabase/seed.sql from src/lib/content/defaults.ts so the database
 * seed and the offline fallback never drift apart.
 *
 *   npm run db:seed:generate
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  DEFAULT_ADD_ONS,
  DEFAULT_PACKAGES,
  DEFAULT_SERVICE_AREAS,
  DEFAULT_SERVICES,
  DEFAULT_SETTINGS,
} from "../../src/lib/content/defaults";
import { SAMPLE_AGENCY_TESTIMONIALS, SAMPLE_CASE_STUDIES as SAMPLE_ONLY_CASES, SAMPLE_CLIENTS as SAMPLE_ONLY_CLIENTS } from "../../src/lib/content/samples";
import { REAL_CASE_STUDIES, REAL_CLIENTS } from "../../src/lib/content/work";

const SAMPLE_CASE_STUDIES = [...REAL_CASE_STUDIES, ...SAMPLE_ONLY_CASES];
const SAMPLE_CLIENTS = [...REAL_CLIENTS, ...SAMPLE_ONLY_CLIENTS];

type Value = string | number | boolean | null | undefined | string[] | object;

const JSONB_COLUMNS = new Set([
  "gallery", "price_tiers", "scheduling_rules", "payment_options", "scheduling", "referral_program",
  "notifications", "analytics", "social_links", "service_area_policy", "metrics", "marketing",
]);

function lit(value: Value, column = ""): string {
  if (value === null || value === undefined) return "null";
  if (JSONB_COLUMNS.has(column)) return `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`;
  if (typeof value === "boolean") return value ? "true" : "false";
  if (typeof value === "number") return String(value);
  if (typeof value === "string") return `'${value.replace(/'/g, "''")}'`;
  if (Array.isArray(value) && value.every((v) => typeof v === "string")) {
    return value.length ? `array[${value.map((v) => lit(v)).join(", ")}]::text[]` : `'{}'::text[]`;
  }
  return `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`;
}

function insert(table: string, rows: Record<string, Value>[], conflict = "id"): string {
  if (!rows.length) return "";
  const columns = Object.keys(rows[0]);
  const values = rows.map((row) => `  (${columns.map((c) => lit(row[c], c)).join(", ")})`).join(",\n");
  return `insert into public.${table} (${columns.join(", ")}) values\n${values}\non conflict (${conflict}) do nothing;\n`;
}

const s = DEFAULT_SETTINGS;
const parts: string[] = [
  "-- Generated by scripts/db/generate-seed.ts from src/lib/content/defaults.ts — do not edit by hand.",
  "-- Sample portfolio projects and testimonials are flagged is_sample and are hidden in",
  "-- production unless SHOW_SAMPLE_CONTENT=true. Replace them with real work before launch.\n",
  insert("business_settings", [
    {
      id: 1,
      business_name: s.business_name,
      tagline: s.tagline,
      email: s.email,
      phone: s.phone,
      city: s.city,
      state: s.state,
      country: s.country,
      latitude: s.latitude,
      longitude: s.longitude,
      timezone: s.timezone,
      currency: s.currency,
      tax_rate_bps: s.tax_rate_bps,
      tax_label: s.tax_label,
      tax_travel_fee: s.tax_travel_fee,
      payment_options: s.payment_options,
      scheduling: s.scheduling,
      referral_program: s.referral_program,
      notifications: s.notifications,
      analytics: s.analytics,
      social_links: s.social_links,
      service_area_policy: s.service_area_policy,
      marketing: s.marketing,
    },
  ]),
  insert(
    "services",
    DEFAULT_SERVICES.map((x) => ({
      id: x.id,
      slug: x.slug,
      name: x.name,
      category: x.category,
      tagline: x.tagline,
      description: x.description,
      features: x.features,
      icon: x.icon,
      image_url: x.image_url,
      gallery: x.gallery,
      pricing_model: x.pricing_model,
      base_price_cents: x.base_price_cents,
      price_tiers: x.price_tiers,
      unit_label: x.unit_label,
      max_quantity: x.max_quantity,
      duration_minutes: x.duration_minutes,
      turnaround_hours: x.turnaround_hours,
      scheduling_rules: x.scheduling_rules,
      is_bookable: x.is_bookable,
      is_addon_eligible: x.is_addon_eligible,
      is_featured: x.is_featured,
      is_active: x.is_active,
      sort_order: x.sort_order,
    }))
  ),
  insert(
    "packages",
    DEFAULT_PACKAGES.map((p) => ({
      id: p.id,
      slug: p.slug,
      name: p.name,
      tagline: p.tagline,
      description: p.description,
      features: p.features,
      base_price_cents: p.base_price_cents,
      price_tiers: p.price_tiers,
      badge: p.badge,
      image_url: p.image_url,
      turnaround_text: p.turnaround_text,
      is_featured: p.is_featured,
      is_active: p.is_active,
      sort_order: p.sort_order,
    }))
  ),
  insert(
    "package_services",
    DEFAULT_PACKAGES.flatMap((p) =>
      p.services.map((ps) => ({ package_id: p.id, service_id: ps.service_id, quantity: ps.quantity }))
    ),
    "package_id, service_id"
  ),
  insert(
    "add_ons",
    DEFAULT_ADD_ONS.map((a) => ({
      id: a.id,
      slug: a.slug,
      name: a.name,
      description: a.description,
      service_id: a.service_id,
      pricing_model: a.pricing_model,
      price_cents: a.price_cents,
      price_tiers: a.price_tiers,
      unit_label: a.unit_label,
      max_quantity: a.max_quantity,
      duration_minutes: a.duration_minutes,
      icon: a.icon,
      show_always: a.show_always,
      is_active: a.is_active,
      sort_order: a.sort_order,
    }))
  ),
  insert(
    "add_on_triggers",
    DEFAULT_ADD_ONS.flatMap((a) => a.trigger_service_ids.map((service_id) => ({ add_on_id: a.id, service_id }))),
    "add_on_id, service_id"
  ),
  insert(
    "service_areas",
    DEFAULT_SERVICE_AREAS.map((a) => ({
      id: a.id,
      name: a.name,
      market: a.market,
      kind: a.kind,
      state: a.state,
      cities: a.cities,
      postal_codes: a.postal_codes,
      center_latitude: a.center_latitude,
      center_longitude: a.center_longitude,
      radius_miles: a.radius_miles,
      travel_fee_cents: a.travel_fee_cents,
      per_mile_cents: a.per_mile_cents,
      free_miles: a.free_miles,
      priority: a.priority,
      is_active: a.is_active,
      notes: a.notes,
    }))
  ),
  insert(
    "portfolio_projects",
    SAMPLE_CASE_STUDIES.map((p) => ({
      id: p.id,
      slug: p.slug,
      title: p.title,
      client_name: p.client_name,
      industry: p.industry,
      year: p.year,
      headline: p.headline,
      summary: p.summary,
      description: p.description,
      categories: p.categories,
      services_performed: p.services_performed,
      metrics: p.metrics,
      challenge: p.challenge,
      strategy: p.strategy,
      execution: p.execution,
      results: p.results,
      cover_image_url: p.cover_image_url,
      hover_video_url: p.hover_video_url,
      video_url: p.video_url,
      city: p.city,
      state: p.state,
      testimonial_quote: p.testimonial_quote,
      testimonial_author: p.testimonial_author,
      testimonial_role: p.testimonial_role,
      is_featured: p.is_featured,
      is_published: p.is_published,
      is_sample: p.is_sample,
      sort_order: p.sort_order,
    }))
  ),
  insert(
    "portfolio_media",
    SAMPLE_CASE_STUDIES.flatMap((p) =>
      p.media.map((m) => ({ id: m.id, project_id: p.id, kind: m.kind, url: m.url, alt: m.alt, sort_order: m.sort_order }))
    )
  ),
  insert(
    "testimonials",
    SAMPLE_AGENCY_TESTIMONIALS.map((t) => ({
      id: t.id,
      author_name: t.author_name,
      author_title: t.author_title,
      company: t.company,
      quote: t.quote,
      rating: t.rating,
      is_featured: t.is_featured,
      is_published: t.is_published,
      is_sample: t.is_sample,
      sort_order: t.sort_order,
    }))
  ),
  insert(
    "clients",
    SAMPLE_CLIENTS.map((c) => ({ id: c.id, name: c.name, sort_order: c.sort_order, is_published: c.is_published, is_sample: c.is_sample }))
  ),
];

const out = join(process.cwd(), "supabase", "seed.sql");
writeFileSync(out, parts.filter(Boolean).join("\n"));
console.log(`Wrote ${out}`);
