/**
 * Default catalog, settings and sample content.
 *
 * Single source of truth for:
 *   - supabase/seed.sql   (generated: `npm run db:seed:generate`)
 *   - the offline fallback used when Supabase isn't configured (local preview)
 *
 * Everything here is editable later from the admin dashboard.
 */
import type {
  AddOn,
  BusinessSettings,
  Package,
  PriceTier,
  Service,
  ServiceArea,
} from "@/lib/types";
import { IMAGES } from "./images";
import { BRAND } from "@/lib/brand";
import { HERO_VIDEO, SHOWREEL_FILM } from "./work";

const $ = (dollars: number) => Math.round(dollars * 100);
const tiers = (...pairs: [number | null, number][]): PriceTier[] =>
  pairs.map(([max_sqft, dollars]) => ({ max_sqft, price_cents: $(dollars) }));

/* ----------------------------------------------------------------------------
 * Business settings
 * -------------------------------------------------------------------------- */
export const DEFAULT_SETTINGS: BusinessSettings = {
  business_name: BRAND.name,
  legal_name: null,
  tagline: BRAND.tagline,
  email: "natejennings99@gmail.com",
  phone: null,
  address_line1: null,
  address_line2: null,
  city: "Tampa",
  state: "FL",
  postal_code: null,
  country: "US",
  latitude: 27.9506,
  longitude: -82.4572,
  timezone: "America/New_York",
  currency: "usd",
  tax_rate_bps: 0,
  tax_label: "Sales tax",
  tax_travel_fee: false,
  payment_options: {
    allow_full: true,
    allow_deposit: true,
    allow_pay_later: true,
    deposit_type: "percent",
    deposit_value: 30,
    pay_later_note: "Pay securely online once your media is ready — before download.",
  },
  scheduling: {
    working_hours: {
      "0": [],
      "1": [{ start: "08:00", end: "18:00" }],
      "2": [{ start: "08:00", end: "18:00" }],
      "3": [{ start: "08:00", end: "18:00" }],
      "4": [{ start: "08:00", end: "18:00" }],
      "5": [{ start: "08:00", end: "18:00" }],
      "6": [{ start: "09:00", end: "16:00" }],
    },
    slot_interval_minutes: 30,
    max_shoots_per_day: 6,
    travel_buffer_minutes: 30,
    default_duration_minutes: 60,
    min_notice_hours: 18,
    max_advance_days: 60,
    hold_minutes: 35,
    twilight_lead_minutes: 25,
  },
  referral_program: {
    enabled: true,
    referrer_reward_cents: $(50),
    referee_discount_type: "fixed",
    referee_discount_value: $(25),
    qualify_on: "paid",
  },
  notifications: {
    admin_emails: ["natejennings99@gmail.com"],
    reminder_hours_before: 24,
    sms_enabled: false,
    reply_to: "natejennings99@gmail.com",
  },
  analytics: { ga4_id: "", meta_pixel_id: "", google_ads_id: "", google_ads_booking_label: "" },
  social_links: { instagram: BRAND.instagram, facebook: "", youtube: "", tiktok: "", linkedin: "" },
  service_area_policy: {
    outside_area_policy: "quote",
    outside_area_fee_cents: $(75),
    road_distance_factor: 1.25,
  },
  hero_video_url: HERO_VIDEO,
  hero_image_url: null,
  marketing: {
    // Real, conservative numbers from our own shoots and feed — update in Admin → Settings → Website.
    stats: [
      { prefix: "", value: 50, suffix: "+", label: "Properties filmed & photographed" },
      { prefix: "", value: 8.5, suffix: "K", label: "Followers on our own feed", decimals: 1 },
      { prefix: "", value: 4, suffix: "K", label: "Capture on every shoot" },
    ],
    stats_are_sample: false,
    trust_line: "Trusted by brokerages, realtors & entrepreneurs in every industry",
    showreel_url: SHOWREEL_FILM,
  },
};

/* ----------------------------------------------------------------------------
 * Services
 * -------------------------------------------------------------------------- */
const SID = {
  photography: "5e000000-0000-4000-8000-000000000001",
  dronePhotos: "5e000000-0000-4000-8000-000000000002",
  droneVideo: "5e000000-0000-4000-8000-000000000003",
  cinematic: "5e000000-0000-4000-8000-000000000004",
  reel: "5e000000-0000-4000-8000-000000000005",
  matterport: "5e000000-0000-4000-8000-000000000006",
  floorPlan: "5e000000-0000-4000-8000-000000000007",
  virtualTwilight: "5e000000-0000-4000-8000-000000000008",
  twilight: "5e000000-0000-4000-8000-000000000009",
  website: "5e000000-0000-4000-8000-000000000010",
  marketingKit: "5e000000-0000-4000-8000-000000000011",
  branding: "5e000000-0000-4000-8000-000000000012",
} as const;

type ServiceSeed = Omit<
  Service,
  "gallery" | "is_active" | "is_addon_eligible" | "seo_title" | "seo_description" | "max_quantity" | "unit_label"
> &
  Partial<Pick<Service, "gallery" | "is_addon_eligible" | "max_quantity" | "unit_label">>;

function service(s: ServiceSeed): Service {
  return {
    gallery: [],
    is_addon_eligible: true,
    max_quantity: null,
    unit_label: null,
    ...s,
    is_active: true,
    seo_title: null,
    seo_description: null,
  };
}

export const DEFAULT_SERVICES: Service[] = [
  service({
    id: SID.photography,
    slug: "photography",
    name: "Professional Photography",
    category: "photography",
    tagline: "Bright, true-to-life HDR photos, hand-edited and delivered the next morning.",
    description:
      "Every room is bracketed, blended and edited by hand for balanced windows, straight verticals and accurate color. You get MLS-sized and print-ready files, organized in the order buyers walk the home.",
    features: [
      "25–60 hand-edited HDR images",
      "Window pulls, sky replacement & color correction",
      "MLS-ready and full-resolution print files",
      "Delivered by 9 AM the next morning",
    ],
    icon: "camera",
    image_url: IMAGES.livingBright,
    gallery: [
      { url: IMAGES.kitchenModern, alt: "Bright modern kitchen" },
      { url: IMAGES.bedroomSuite, alt: "Primary suite" },
      { url: IMAGES.bathMarble, alt: "Marble bathroom" },
    ],
    pricing_model: "sqft",
    base_price_cents: $(175),
    price_tiers: tiers([1500, 175], [2500, 199], [3500, 239], [5000, 289], [null, 349]),
    duration_minutes: 75,
    turnaround_hours: 24,
    scheduling_rules: {},
    is_bookable: true,
    is_featured: true,
    sort_order: 10,
  }),
  service({
    id: SID.dronePhotos,
    slug: "drone-photography",
    name: "Drone Photography",
    category: "drone",
    tagline: "Drone aerials that show the lot, the views and the neighborhood.",
    description:
      "Elevated and high-altitude angles reveal what ground photos can't: lot size, water and golf views, proximity to amenities. Optional lot-line overlays on request.",
    features: ["10–15 aerial images", "4K aerial footage and stills", "Lot-line overlays available", "Neighborhood context shots"],
    icon: "plane",
    image_url: IMAGES.aerialSuburb,
    gallery: [{ url: IMAGES.aerialCoast, alt: "Coastal aerial" }],
    pricing_model: "flat",
    base_price_cents: $(125),
    price_tiers: [],
    duration_minutes: 20,
    turnaround_hours: 24,
    scheduling_rules: { daylight_only: true, requires_skill: "drone" },
    is_bookable: true,
    is_featured: true,
    sort_order: 20,
  }),
  service({
    id: SID.droneVideo,
    slug: "drone-video",
    name: "Drone Video",
    category: "drone",
    tagline: "Sweeping 4K aerial footage cut into a 60–90 second film.",
    description:
      "Smooth reveals, orbits and fly-throughs of the property and surrounding area, color graded and edited to licensed music. Branded and unbranded (MLS) versions included.",
    features: ["60–90 second edit", "4K, color graded", "Licensed music", "Branded + MLS-unbranded versions"],
    icon: "clapperboard",
    image_url: IMAGES.droneFlying,
    pricing_model: "flat",
    base_price_cents: $(199),
    price_tiers: [],
    duration_minutes: 25,
    turnaround_hours: 48,
    scheduling_rules: { daylight_only: true, requires_skill: "drone" },
    is_bookable: true,
    is_featured: false,
    sort_order: 30,
  }),
  service({
    id: SID.cinematic,
    slug: "cinematic-video",
    name: "Cinematic Property Video",
    category: "video",
    tagline: "A gimbal-shot listing film with story, motion and music.",
    description:
      "A 1–2 minute film shot in 4K on a stabilized gimbal, sequenced like a showing and finished with color grading and licensed music. Optional agent intro on camera.",
    features: ["1–2 minute 4K film", "Gimbal-stabilized motion", "Color grading & licensed music", "Optional agent on-camera intro"],
    icon: "film",
    image_url: IMAGES.videoRig,
    pricing_model: "sqft",
    base_price_cents: $(349),
    price_tiers: tiers([2500, 349], [4000, 425], [null, 525]),
    duration_minutes: 60,
    turnaround_hours: 48,
    scheduling_rules: { requires_skill: "video" },
    is_bookable: true,
    is_featured: true,
    sort_order: 40,
  }),
  service({
    id: SID.reel,
    slug: "social-media-reel",
    name: "Vertical Realtor Reel",
    category: "video",
    tagline: "A scroll-stopping 9:16 reel for Instagram, TikTok and Shorts.",
    description:
      "Fast-paced vertical edits built for social: hook in the first second, captions, trending-style pacing and an optional agent cameo.",
    features: ["30–60 second 9:16 edit", "On-screen captions", "Hook-first pacing", "Ready to post"],
    icon: "smartphone",
    image_url: IMAGES.phoneSocial,
    pricing_model: "flat",
    base_price_cents: $(199),
    price_tiers: [],
    duration_minutes: 30,
    turnaround_hours: 48,
    scheduling_rules: { requires_skill: "video" },
    is_bookable: true,
    is_featured: true,
    sort_order: 50,
  }),
  service({
    id: SID.matterport,
    slug: "matterport-3d-tour",
    name: "Matterport 3D Tour",
    category: "tour",
    tagline: "An immersive walkthrough buyers can explore from anywhere, 24/7.",
    description:
      "A Matterport Pro scan with dollhouse view, floor-plan view and measurement mode. Branded and MLS-compliant unbranded links, hosted for six months.",
    features: ["Dollhouse & floor-plan views", "Branded + unbranded links", "Embeddable anywhere", "Hosted for 6 months"],
    icon: "box",
    image_url: IMAGES.livingModern,
    pricing_model: "sqft",
    base_price_cents: $(199),
    price_tiers: tiers([2000, 199], [3500, 249], [5000, 299], [null, 379]),
    duration_minutes: 60,
    turnaround_hours: 48,
    scheduling_rules: { min_notice_hours: 24, requires_skill: "tour" },
    is_bookable: true,
    is_featured: true,
    sort_order: 60,
  }),
  service({
    id: SID.floorPlan,
    slug: "floor-plans",
    name: "Floor Plans",
    category: "floor_plan",
    tagline: "Accurate 2D plans with room dimensions and total square footage.",
    description:
      "Laser-measured floor plans drawn to scale, with room names, dimensions and total living area. Delivered as high-resolution PNG and PDF.",
    features: ["Laser-measured", "Room dimensions & totals", "PNG + PDF", "Branded or unbranded"],
    icon: "ruler",
    image_url: IMAGES.blueprint,
    pricing_model: "sqft",
    base_price_cents: $(89),
    price_tiers: tiers([2000, 89], [3500, 119], [null, 149]),
    duration_minutes: 20,
    turnaround_hours: 24,
    scheduling_rules: {},
    is_bookable: true,
    is_featured: true,
    sort_order: 70,
  }),
  service({
    id: SID.virtualTwilight,
    slug: "virtual-twilight",
    name: "Virtual Twilight",
    category: "editing",
    tagline: "Turn a daytime exterior into a glowing golden-hour hero shot.",
    description:
      "Our editors convert daytime exteriors into realistic dusk scenes: warm interior glow, dramatic sky and landscape lighting — without a second visit.",
    features: ["Realistic dusk sky", "Warm window glow", "No return visit needed", "Delivered with your photos"],
    icon: "sunset",
    image_url: IMAGES.villaTwilight,
    pricing_model: "per_unit",
    base_price_cents: $(35),
    price_tiers: [],
    unit_label: "image",
    max_quantity: 10,
    duration_minutes: 0,
    turnaround_hours: 24,
    scheduling_rules: {},
    is_bookable: true,
    is_featured: true,
    sort_order: 80,
  }),
  service({
    id: SID.twilight,
    slug: "twilight-photography",
    name: "Twilight Photography",
    category: "photography",
    tagline: "An on-site golden-hour session when the home looks its best.",
    description:
      "We arrive before sunset and capture the exterior (and key interiors) as the sky turns deep blue and the home glows. Scheduled automatically around the day's sunset.",
    features: ["Scheduled around sunset", "8–12 twilight images", "Exterior & key interiors", "Weather-guaranteed reschedule"],
    icon: "moon",
    image_url: IMAGES.exteriorDusk,
    pricing_model: "flat",
    base_price_cents: $(249),
    price_tiers: [],
    duration_minutes: 45,
    turnaround_hours: 24,
    scheduling_rules: { twilight: true },
    is_bookable: true,
    is_featured: false,
    sort_order: 90,
  }),
  service({
    id: SID.website,
    slug: "property-website",
    name: "Property Website",
    category: "web",
    tagline: "A beautiful single-property site with gallery, video, tour and lead capture.",
    description:
      "A mobile-first listing website generated from your delivered media, with a shareable link, QR code for signage and an unbranded version for the MLS.",
    features: ["Gallery, video & 3D tour", "Shareable link + QR code", "Branded & unbranded", "Live within 24 hours"],
    icon: "globe",
    image_url: IMAGES.exteriorModern,
    pricing_model: "flat",
    base_price_cents: $(79),
    price_tiers: [],
    duration_minutes: 0,
    turnaround_hours: 24,
    scheduling_rules: {},
    is_bookable: true,
    is_featured: true,
    sort_order: 100,
  }),
  service({
    id: SID.marketingKit,
    slug: "marketing-kit",
    name: "Marketing Kit",
    category: "marketing",
    tagline: "Flyers, social graphics and ‘Just Listed’ posts, ready to share.",
    description:
      "A designed launch kit built from your listing media: print flyer, feature sheet, Instagram carousel and story graphics, plus ‘Just Listed’ and ‘Under Contract’ posts.",
    features: ["Print flyer & feature sheet", "Social carousel & stories", "Just Listed / Sold posts", "Editable templates"],
    icon: "layout-template",
    image_url: IMAGES.kitchenChef,
    pricing_model: "flat",
    base_price_cents: $(99),
    price_tiers: [],
    duration_minutes: 0,
    turnaround_hours: 48,
    scheduling_rules: {},
    is_bookable: true,
    is_featured: true,
    sort_order: 110,
  }),
  service({
    id: SID.branding,
    slug: "agent-branding",
    name: "Agent Branding Content",
    category: "branding",
    tagline: "Headshots and personal-brand video that make you instantly recognizable.",
    description:
      "Studio-quality headshots, lifestyle portraits and short intro videos for your website, listings and social channels. Custom-quoted for individuals and teams.",
    features: ["Headshots & lifestyle portraits", "Intro & about-me videos", "Team sessions", "Custom quote"],
    icon: "user-round",
    image_url: IMAGES.agentPortrait,
    pricing_model: "flat",
    base_price_cents: $(349),
    price_tiers: [],
    duration_minutes: 90,
    turnaround_hours: 72,
    scheduling_rules: {},
    is_bookable: false,
    is_addon_eligible: false,
    is_featured: false,
    sort_order: 120,
  }),
];

/* ----------------------------------------------------------------------------
 * Packages
 * -------------------------------------------------------------------------- */
export const DEFAULT_PACKAGES: Package[] = [
  {
    id: "9a000000-0000-4000-8000-000000000001",
    slug: "essential",
    name: "Essential",
    tagline: "Everything a listing needs to go live tomorrow.",
    description: "Professional listing photography and a clean floor plan — the essentials, done beautifully.",
    features: ["Professional listing photography", "Basic 2D floor plan", "Next-day delivery", "MLS-ready sizing"],
    base_price_cents: $(250),
    price_tiers: tiers([2500, 250], [3500, 295], [5000, 345], [null, 425]),
    badge: null,
    image_url: IMAGES.livingModern,
    turnaround_text: "Next-day delivery",
    is_featured: false,
    is_active: true,
    sort_order: 10,
    services: [
      { service_id: SID.photography, quantity: 1 },
      { service_id: SID.floorPlan, quantity: 1 },
    ],
  },
  {
    id: "9a000000-0000-4000-8000-000000000002",
    slug: "pro",
    name: "Pro",
    tagline: "Photos, aerials and a full marketing launch in one visit.",
    description: "Our most-booked package: ground and aerial photography, a floor plan, a property website and a ready-to-post marketing kit.",
    features: ["Professional photography", "Drone photography", "Floor plan", "Property website", "Marketing kit"],
    base_price_cents: $(450),
    price_tiers: tiers([2500, 450], [3500, 515], [5000, 595], [null, 725]),
    badge: "Most popular",
    image_url: IMAGES.aerialSuburb,
    turnaround_text: "Photos next day · kit in 48h",
    is_featured: true,
    is_active: true,
    sort_order: 20,
    services: [
      { service_id: SID.photography, quantity: 1 },
      { service_id: SID.dronePhotos, quantity: 1 },
      { service_id: SID.floorPlan, quantity: 1 },
      { service_id: SID.website, quantity: 1 },
      { service_id: SID.marketingKit, quantity: 1 },
    ],
  },
  {
    id: "9a000000-0000-4000-8000-000000000003",
    slug: "signature",
    name: "Signature",
    tagline: "The cinematic launch for listings that deserve a premiere.",
    description: "Everything in Pro plus a cinematic property film and a vertical reel built for social reach.",
    features: [
      "Professional photography",
      "Drone photography",
      "Cinematic property video",
      "Vertical social media reel",
      "Floor plan",
      "Property website",
      "Marketing kit",
    ],
    base_price_cents: $(650),
    price_tiers: tiers([2500, 650], [3500, 750], [5000, 875], [null, 1050]),
    badge: "Best value",
    image_url: IMAGES.villaTwilight,
    turnaround_text: "Photos next day · film in 48h",
    is_featured: false,
    is_active: true,
    sort_order: 30,
    services: [
      { service_id: SID.photography, quantity: 1 },
      { service_id: SID.dronePhotos, quantity: 1 },
      { service_id: SID.cinematic, quantity: 1 },
      { service_id: SID.reel, quantity: 1 },
      { service_id: SID.floorPlan, quantity: 1 },
      { service_id: SID.website, quantity: 1 },
      { service_id: SID.marketingKit, quantity: 1 },
    ],
  },
];

/* ----------------------------------------------------------------------------
 * Add-ons (linked add-ons reuse their service's price)
 * -------------------------------------------------------------------------- */
type AddOnSeed = Pick<AddOn, "id" | "slug" | "name" | "description" | "trigger_service_ids"> & Partial<AddOn>;
function addOn(a: AddOnSeed): AddOn {
  return {
    service_id: null,
    pricing_model: "flat",
    price_cents: 0,
    price_tiers: [],
    unit_label: null,
    max_quantity: null,
    duration_minutes: 0,
    icon: null,
    show_always: false,
    is_active: true,
    sort_order: 0,
    ...a,
  };
}

const AID = (n: number) => `ad000000-0000-4000-8000-${String(n).padStart(12, "0")}`;

export const DEFAULT_ADD_ONS: AddOn[] = [
  addOn({ id: AID(1), slug: "drone-photos", name: "Drone Photos", description: "Aerial stills of the home, lot and surroundings.", service_id: SID.dronePhotos, icon: "plane", sort_order: 10, trigger_service_ids: [SID.photography, SID.cinematic] }),
  addOn({ id: AID(2), slug: "twilight-shoot", name: "Twilight Photography", description: "Return at golden hour for glowing exteriors.", service_id: SID.twilight, icon: "moon", sort_order: 20, trigger_service_ids: [SID.photography] }),
  addOn({ id: AID(3), slug: "floor-plan", name: "Floor Plan", description: "Measured 2D plan with room dimensions.", service_id: SID.floorPlan, icon: "ruler", sort_order: 30, trigger_service_ids: [SID.photography, SID.matterport] }),
  addOn({ id: AID(4), slug: "virtual-twilight", name: "Virtual Twilight", description: "Day-to-dusk edit of your best exterior.", service_id: SID.virtualTwilight, icon: "sunset", sort_order: 40, trigger_service_ids: [SID.photography, SID.dronePhotos] }),
  addOn({ id: AID(5), slug: "property-website", name: "Property Website", description: "A shareable single-property site.", service_id: SID.website, icon: "globe", sort_order: 50, trigger_service_ids: [SID.photography, SID.cinematic, SID.matterport] }),
  addOn({ id: AID(6), slug: "social-reel", name: "Social Media Reel", description: "A vertical reel ready for Instagram & TikTok.", service_id: SID.reel, icon: "smartphone", sort_order: 60, trigger_service_ids: [SID.photography, SID.cinematic, SID.droneVideo] }),
  addOn({ id: AID(7), slug: "drone-video", name: "Drone Video", description: "4K aerial footage edited to music.", service_id: SID.droneVideo, icon: "clapperboard", sort_order: 70, trigger_service_ids: [SID.cinematic, SID.dronePhotos, SID.reel] }),
  addOn({ id: AID(8), slug: "matterport", name: "Matterport 3D Tour", description: "Immersive 3D walkthrough with dollhouse view.", service_id: SID.matterport, icon: "box", sort_order: 80, trigger_service_ids: [SID.photography, SID.floorPlan] }),
  addOn({ id: AID(9), slug: "marketing-kit", name: "Marketing Kit", description: "Flyers and social graphics from your photos.", service_id: SID.marketingKit, icon: "layout-template", sort_order: 90, trigger_service_ids: [SID.photography] }),
  addOn({ id: AID(10), slug: "additional-photos", name: "Additional Photos", description: "Ten more hand-edited images for larger homes.", pricing_model: "per_unit", price_cents: $(30), unit_label: "set of 10", max_quantity: 5, duration_minutes: 10, icon: "images", sort_order: 100, trigger_service_ids: [SID.photography] }),
  addOn({ id: AID(11), slug: "rush-delivery", name: "Rush Delivery", description: "Same-day delivery for shoots finished before 1 PM.", price_cents: $(75), icon: "zap", show_always: true, sort_order: 110, trigger_service_ids: [] }),
  addOn({ id: AID(12), slug: "key-pickup", name: "Key Pickup", description: "We collect keys from your office and return them.", price_cents: $(25), duration_minutes: 20, icon: "key-round", show_always: true, sort_order: 120, trigger_service_ids: [] }),
];

/* ----------------------------------------------------------------------------
 * Service areas (example market — edit in Admin → Settings → Service areas)
 * -------------------------------------------------------------------------- */
export const DEFAULT_SERVICE_AREAS: ServiceArea[] = [
  {
    id: "5a000000-0000-4000-8000-000000000001",
    name: "Tampa Bay core",
    market: "Tampa Bay",
    kind: "primary",
    state: "FL",
    cities: ["tampa", "st petersburg", "saint petersburg", "clearwater", "brandon", "riverview", "lutz", "largo", "temple terrace", "wesley chapel", "apollo beach", "palm harbor", "dunedin", "oldsmar", "valrico"],
    postal_codes: [],
    center_latitude: 27.9506,
    center_longitude: -82.4572,
    radius_miles: 25,
    travel_fee_cents: 0,
    per_mile_cents: 0,
    free_miles: 25,
    priority: 10,
    is_active: true,
    notes: "No travel fee inside the core market.",
  },
  {
    id: "5a000000-0000-4000-8000-000000000002",
    name: "Extended Tampa Bay",
    market: "Tampa Bay",
    kind: "travel_zone",
    state: "FL",
    cities: ["sarasota", "bradenton", "lakeland", "spring hill", "new port richey", "plant city", "zephyrhills", "tarpon springs", "land o lakes", "ruskin", "sun city center"],
    postal_codes: [],
    center_latitude: 27.9506,
    center_longitude: -82.4572,
    radius_miles: 65,
    travel_fee_cents: $(35),
    per_mile_cents: 150,
    free_miles: 25,
    priority: 20,
    is_active: true,
    notes: "$35 + $1.50/mile beyond 25 miles.",
  },  {
    id: "5a000000-0000-4000-8000-000000000003",
    name: "Washington, DC",
    market: "DMV",
    kind: "primary",
    state: "DC",
    cities: ["washington"],
    postal_codes: [],
    center_latitude: 38.9072,
    center_longitude: -77.0369,
    radius_miles: 12,
    travel_fee_cents: 0,
    per_mile_cents: 0,
    free_miles: 25,
    priority: 5,
    is_active: true,
    notes: "No travel fee in the District.",
  },
  {
    id: "5a000000-0000-4000-8000-000000000004",
    name: "Northern Virginia",
    market: "DMV",
    kind: "primary",
    state: "VA",
    cities: ["arlington", "alexandria", "falls church", "mclean", "great falls", "vienna", "fairfax", "reston", "herndon", "annandale", "springfield", "burke", "oakton", "chantilly", "centreville", "tysons", "lorton"],
    postal_codes: [],
    center_latitude: 38.8816,
    center_longitude: -77.091,
    radius_miles: 25,
    travel_fee_cents: 0,
    per_mile_cents: 0,
    free_miles: 25,
    priority: 6,
    is_active: true,
    notes: "No travel fee inside the Beltway region.",
  },
  {
    id: "5a000000-0000-4000-8000-000000000005",
    name: "Maryland suburbs",
    market: "DMV",
    kind: "primary",
    state: "MD",
    cities: ["bethesda", "silver spring", "rockville", "chevy chase", "takoma park", "potomac", "gaithersburg", "kensington", "wheaton", "germantown", "north bethesda", "college park", "hyattsville", "bowie"],
    postal_codes: [],
    center_latitude: 38.9847,
    center_longitude: -77.0947,
    radius_miles: 22,
    travel_fee_cents: 0,
    per_mile_cents: 0,
    free_miles: 25,
    priority: 7,
    is_active: true,
    notes: "No travel fee in Montgomery and Prince George's.",
  },
  {
    id: "5a000000-0000-4000-8000-000000000006",
    name: "Extended Northern Virginia",
    market: "DMV",
    kind: "travel_zone",
    state: "VA",
    cities: ["leesburg", "ashburn", "sterling", "manassas", "woodbridge", "dumfries", "gainesville", "haymarket", "stafford", "fredericksburg", "warrenton"],
    postal_codes: [],
    center_latitude: 38.9072,
    center_longitude: -77.0369,
    radius_miles: 60,
    travel_fee_cents: $(35),
    per_mile_cents: 150,
    free_miles: 25,
    priority: 15,
    is_active: true,
    notes: "$35 + $1.50/mile beyond 25 miles.",
  },
  {
    id: "5a000000-0000-4000-8000-000000000007",
    name: "Extended Maryland",
    market: "DMV",
    kind: "travel_zone",
    state: "MD",
    cities: ["frederick", "annapolis", "columbia", "laurel", "waldorf", "upper marlboro", "clarksburg", "olney", "ellicott city", "baltimore"],
    postal_codes: [],
    center_latitude: 38.9072,
    center_longitude: -77.0369,
    radius_miles: 60,
    travel_fee_cents: $(35),
    per_mile_cents: 150,
    free_miles: 25,
    priority: 16,
    is_active: true,
    notes: "$35 + $1.50/mile beyond 25 miles.",
  },
];

export const DEFAULT_IDS = { services: SID };
