/**
 * SAMPLE agency content used to demo the site. Every record is flagged
 * `is_sample` and hidden in production unless SHOW_SAMPLE_CONTENT=true.
 * The brands, people and results below are fictional — replace them with real
 * client work in Admin → Work / Testimonials / Clients before launch.
 */
import type { Client, PortfolioProject, Testimonial } from "@/lib/types";
import { AGENCY_IMAGES as A } from "./agency-images";
import { IMAGES } from "./images";

let mediaSeq = 0;
const m = (url: string, alt: string) => ({
  id: `92000000-0000-4000-8000-${String(++mediaSeq).padStart(12, "0")}`,
  kind: "photo" as const,
  url,
  poster_url: null,
  alt,
  caption: null,
  width: null,
  height: null,
  sort_order: mediaSeq,
});
const PID = (n: number) => `90000000-0000-4000-8000-${String(n).padStart(12, "0")}`;

type CaseSeed = Pick<
  PortfolioProject,
  "slug" | "title" | "client_name" | "industry" | "year" | "headline" | "summary" | "categories" | "services_performed" | "metrics" | "challenge" | "strategy" | "execution" | "results" | "cover_image_url" | "media" | "testimonial_quote" | "testimonial_author" | "testimonial_role" | "is_featured" | "sort_order"
>;

const caseStudy = (n: number, c: CaseSeed): PortfolioProject => ({
  id: PID(n),
  neighborhood: null,
  city: null,
  state: null,
  property_type: null,
  description: c.summary,
  video_url: null,
  tour_url: null,
  shot_on: null,
  hover_video_url: null,
  is_published: true,
  is_sample: true,
  ...c,
});

export const SAMPLE_CASE_STUDIES: PortfolioProject[] = [
  caseStudy(1, {
    slug: "solenne-hotels",
    title: "Stay for the light",
    client_name: "Solenne Hotels",
    industry: "Hospitality",
    year: 2025,
    headline: "Turning golden hour into a booking engine.",
    summary: "A boutique coastal hotel group was renting its best rooms to online travel agencies at a 20% commission. We rebuilt the brand around the one moment guests never stop photographing — and made booking direct the obvious move.",
    categories: ["branding", "paid-media", "creative"],
    services_performed: ["Brand Strategy", "Paid Media", "Content Production", "Web Design"],
    metrics: [
      { value: "+217%", label: "Direct booking revenue" },
      { value: "4.1x", label: "Return on ad spend" },
      { value: "−38%", label: "OTA dependency" },
    ],
    challenge: "Beautiful properties, forgettable brand. Guests loved the hotels but booked through third-party sites, and every campaign looked like every other resort ad in the feed.",
    strategy: "Own golden hour. We positioned Solenne as the place the day ends best, built a member rate that rewards booking direct, and structured media around dream-trip planning windows instead of last-minute deals.",
    execution: "A three-day production captured sunrise-to-sunset content across four properties: hero films, 60+ vertical cuts and a photo library. A new direct-booking site loads in under a second and turns every page into a reason to book.",
    results: "Direct revenue more than tripled within two seasons while commission costs fell, funding the next wave of creative.",
    cover_image_url: A.hotelPoolDusk,
    media: [m(A.hotelLounge, "Lobby lounge at dusk"), m(A.resortPalms, "Pool deck under palms"), m(A.hotelRoom, "Signature suite"), m(A.hotelDeck, "Poolside at blue hour")],
    testimonial_quote: "They didn't just run our marketing. They changed how we think about growth.",
    testimonial_author: "Camille Reyes",
    testimonial_role: "CMO, Solenne Hotels",
    is_featured: true,
    sort_order: 10,
  }),
  caseStudy(2, {
    slug: "norrow-coffee",
    title: "A morning ritual, rebuilt",
    client_name: "Norrow Coffee Co.",
    industry: "Consumer Brands",
    year: 2025,
    headline: "From farmers-market favorite to national subscription brand.",
    summary: "A small-batch roaster with cult local demand and zero national awareness. We gave the brand a voice as bold as the coffee and a subscription engine to match.",
    categories: ["branding", "social", "creative"],
    services_performed: ["Brand Strategy", "Social Media", "Content Production", "Paid Media"],
    metrics: [
      { value: "4.6x", label: "Return on ad spend" },
      { value: "+182%", label: "Subscription revenue" },
      { value: "2.3M", label: "Organic video views" },
    ],
    challenge: "Great coffee, generic packaging and a website that treated subscriptions as an afterthought.",
    strategy: "Sell the ritual, not the bean. A new identity, a first-subscription offer and a creator program that put Norrow in thousands of real kitchens.",
    execution: "Packaging, a product photography system, and a weekly short-form series filmed in-house — tested hook by hook against paid social audiences.",
    results: "Subscriptions became the majority of revenue within a year, and organic content now fuels the best-performing ads.",
    cover_image_url: A.coffeeTop,
    media: [m(A.coffeeLatte, "Latte art"), m(A.coffeeBeansCup, "Morning cup"), m(A.coffeeBeans, "Fresh roast"), m(A.cafeSign, "Flagship café")],
    testimonial_quote: "The first campaign paid for the year. Everything after that was upside.",
    testimonial_author: "Owen Hart",
    testimonial_role: "Founder, Norrow Coffee Co.",
    is_featured: true,
    sort_order: 20,
  }),
  caseStudy(3, {
    slug: "brightwater-realty",
    title: "Listings that sell before the open house",
    client_name: "Brightwater Realty",
    industry: "Real Estate",
    year: 2026,
    headline: "Every listing launched like a premiere.",
    summary: "A growing brokerage wanted listings — and agents — that stood out in a crowded market. We built a launch system: cinematic media, a property site and paid social for every home.",
    categories: ["creative", "paid-media", "web"],
    services_performed: ["Content Production", "Paid Media", "Web Design", "AI Automation"],
    metrics: [
      { value: "+312%", label: "Qualified buyer leads" },
      { value: "9 days", label: "Median days on market" },
      { value: "−38%", label: "Cost per lead" },
    ],
    challenge: "Listing photos that blended in, lead forms that went unanswered for hours, and agents recruiting with nothing to show.",
    strategy: "Make every listing an event: twilight photography, drone film and a vertical reel, launched with geo-targeted ads and instant AI lead follow-up.",
    execution: "A repeatable production and launch kit — photo, video, 3D tour and property website within 48 hours — plus automated lead routing that answers buyers in under a minute.",
    results: "More qualified buyers per listing, faster sales and a recruiting story the brokerage now leads with.",
    cover_image_url: IMAGES.heroDusk,
    media: [m(IMAGES.villaTwilight, "Home at twilight"), m(IMAGES.livingModern, "Great room"), m(IMAGES.kitchenModern, "Kitchen"), m(IMAGES.aerialSuburb, "Aerial context")],
    testimonial_quote: "Our listings look like film premieres now. Sellers ask for them by name.",
    testimonial_author: "Dana Whitfield",
    testimonial_role: "Managing Broker, Brightwater Realty",
    is_featured: true,
    sort_order: 30,
  }),
  caseStudy(4, {
    slug: "pulse-athletics",
    title: "Built to move",
    client_name: "Pulse Athletics",
    industry: "Lifestyle",
    year: 2025,
    headline: "A boutique gym with a stadium-sized presence.",
    summary: "Three locations competing with national chains. We built a brand with attitude and a membership funnel that fills classes.",
    categories: ["social", "paid-media", "web"],
    services_performed: ["Social Media", "Paid Media", "Web Design", "Growth Strategy"],
    metrics: [
      { value: "+188%", label: "New memberships" },
      { value: "3.2x", label: "Return on ad spend" },
      { value: "−61%", label: "Cost per acquisition" },
    ],
    challenge: "Great coaches, empty 6 a.m. classes and ads that looked like every gym ad ever made.",
    strategy: "Show the sweat. Member-led content, a free first-class offer and landing pages built for one thumb.",
    execution: "A monthly content day, trainer-led vertical series and a booking funnel that converts in three taps.",
    results: "Classes waitlisted at all three locations and a fourth opening funded by the growth.",
    cover_image_url: A.workoutDark,
    media: [m(A.gym, "Training floor"), m(A.workoutFloor, "Core class"), m(A.gymLift, "Strength session")],
    testimonial_quote: "Fast, sharp and honest about the numbers. That's a rare combination.",
    testimonial_author: "Marcus Lee",
    testimonial_role: "CEO, Pulse Athletics",
    is_featured: true,
    sort_order: 40,
  }),
  caseStudy(5, {
    slug: "ember-and-oak",
    title: "A table worth the wait",
    client_name: "Ember & Oak",
    industry: "Restaurants",
    year: 2024,
    headline: "Fully booked, five nights a week.",
    summary: "A chef-driven restaurant with a loyal core and quiet weeknights. We made the dining room the city's favorite piece of content.",
    categories: ["social", "creative"],
    services_performed: ["Social Media", "Content Production"],
    metrics: [
      { value: "+96%", label: "Weeknight reservations" },
      { value: "1.4M", label: "Reel views" },
      { value: "+54%", label: "Private events revenue" },
    ],
    challenge: "Incredible food photographed under fluorescent kitchen light, posted sporadically.",
    strategy: "Behind the pass: the fire, the plating, the people. A consistent weekly cadence and a reservations-first call to action.",
    execution: "Monthly content shoots, chef-hosted reels and a private-events landing page with instant inquiry routing.",
    results: "Weeknights doubled and private dining became the fastest-growing revenue line.",
    cover_image_url: A.restaurantMoody,
    media: [m(A.diningPlate, "Signature plate"), m(A.restaurantBar, "The bar"), m(A.foodBowls, "Shared plates"), m(A.cocktails, "Cocktail program")],
    testimonial_quote: null,
    testimonial_author: null,
    testimonial_role: null,
    is_featured: false,
    sort_order: 50,
  }),
  caseStudy(6, {
    slug: "vector-labs",
    title: "Complex product, simple story",
    client_name: "Vector Labs",
    industry: "Technology",
    year: 2025,
    headline: "Making enterprise AI feel obvious.",
    summary: "A powerful platform explained with jargon. We found the one-sentence story and built a site and content engine around it.",
    categories: ["branding", "web"],
    services_performed: ["Brand Strategy", "Web Design", "SEO + Content"],
    metrics: [
      { value: "+140%", label: "Organic traffic" },
      { value: "2.7x", label: "Demo requests" },
      { value: "−41%", label: "Bounce rate" },
    ],
    challenge: "Buyers couldn't tell what the product did in the first ten seconds.",
    strategy: "Lead with outcomes, prove with product, and publish the answers buyers were already searching for.",
    execution: "Messaging architecture, a new identity system, a Next.js site and a 40-article editorial program.",
    results: "Search became the top pipeline source and sales calls start further down the funnel.",
    cover_image_url: A.laptopDark,
    media: [m(A.circuit, "Hardware detail"), m(A.deskTop, "Product in use"), m(A.earthNight, "Global network")],
    testimonial_quote: null,
    testimonial_author: null,
    testimonial_role: null,
    is_featured: false,
    sort_order: 60,
  }),
  caseStudy(7, {
    slug: "lumiere-skin",
    title: "Glow, engineered",
    client_name: "Lumière Skin",
    industry: "Consumer Brands",
    year: 2024,
    headline: "Clinical skincare that finally looks the part.",
    summary: "Dermatologist-developed formulas in packaging that said drugstore. A rebrand, a launch film and performance media that earned retail shelf space.",
    categories: ["branding", "creative", "paid-media"],
    services_performed: ["Brand Strategy", "Content Production", "Paid Media"],
    metrics: [
      { value: "5.1x", label: "Launch ROAS" },
      { value: "+230%", label: "Retail doors" },
      { value: "3.8M", label: "Launch impressions" },
    ],
    challenge: "Premium results, commodity perception.",
    strategy: "Science you can see: macro product film, clinical proof up front, and a launch built for both DTC and retail buyers.",
    execution: "Identity and packaging, a hero launch film, and a 12-week paid social launch with creator seeding.",
    results: "Sold out the first run and secured national retail placement.",
    cover_image_url: A.facial,
    media: [m(A.skincare, "Hero serum"), m(A.cosmetics, "Ritual"), m(A.cosmeticsFlat, "Collection")],
    testimonial_quote: null,
    testimonial_author: null,
    testimonial_role: null,
    is_featured: false,
    sort_order: 70,
  }),
];

const TID = (n: number) => `7e000000-0000-4000-8000-${String(n).padStart(12, "0")}`;
export const SAMPLE_AGENCY_TESTIMONIALS: Testimonial[] = SAMPLE_CASE_STUDIES.filter((c) => c.testimonial_quote).map((c, i) => ({
  id: TID(i + 1),
  author_name: c.testimonial_author!,
  author_title: c.testimonial_role!.split(",")[0],
  company: c.client_name,
  quote: c.testimonial_quote!,
  rating: 5,
  avatar_url: null,
  is_featured: true,
  is_published: true,
  is_sample: true,
  sort_order: (i + 1) * 10,
}));

const CID = (n: number) => `c1000000-0000-4000-8000-${String(n).padStart(12, "0")}`;
export const SAMPLE_CLIENTS: Client[] = [
  "Solenne Hotels",
  "Norrow Coffee",
  "Brightwater",
  "Pulse Athletics",
  "Ember & Oak",
  "Vector Labs",
  "Lumière",
  "Northfield",
  "Atlas & Vale",
  "Kinetic",
].map((name, i) => ({ id: CID(i + 1), name, logo_url: null, website_url: null, sort_order: (i + 1) * 10, is_published: true, is_sample: true }));
