/**
 * REAL Jennings Media work — footage and photography from our own shoots
 * (web-optimised copies live in /public/media). Copy is factual: it describes
 * what was made, never results we can't back up. Add metrics, results and
 * client quotes in Admin → Work once you have them.
 */
import type { Client, PortfolioProject } from "@/lib/types";
import { BRAND } from "@/lib/brand";

const V = (name: string) => `/media/video/${name}.mp4`;
const W = (name: string) => `/media/work/${name}.jpg`;

let mediaSeq = 0;
const photos = (title: string, urls: string[]) =>
  urls.map((url) => ({
    id: `94000000-0000-4000-8000-${String(++mediaSeq).padStart(12, "0")}`,
    kind: "photo" as const,
    url,
    poster_url: null,
    alt: title,
    caption: null,
    width: null,
    height: null,
    sort_order: mediaSeq,
  }));

type WorkSeed = Pick<
  PortfolioProject,
  "slug" | "title" | "client_name" | "industry" | "year" | "headline" | "summary" | "categories" | "services_performed" | "execution" | "cover_image_url" | "hover_video_url" | "is_featured" | "sort_order"
> & { gallery: string[]; city?: string; state?: string };

const work = (n: number, { gallery, city, state, ...c }: WorkSeed): PortfolioProject => ({
  id: `93000000-0000-4000-8000-${String(n).padStart(12, "0")}`,
  neighborhood: null,
  city: city ?? null,
  state: state ?? null,
  property_type: null,
  description: c.summary,
  video_url: c.hover_video_url,
  tour_url: null,
  shot_on: null,
  metrics: [],
  challenge: null,
  strategy: null,
  results: null,
  testimonial_quote: null,
  testimonial_author: null,
  testimonial_role: null,
  is_published: true,
  is_sample: false,
  media: photos(c.title, gallery),
  ...c,
});

export const REAL_CASE_STUDIES: PortfolioProject[] = [
  work(1, {
    slug: "elevate-property-group",
    title: "Elevate Property Group",
    client_name: "Elevate Property Group",
    industry: "Real Estate",
    year: 2025,
    headline: "A brokerage brand, told by its people.",
    summary: "A brand film for Elevate Property Group — the team, the culture and the energy behind the brokerage — cut vertical-first for Instagram and Reels, plus photo and video coverage of the team's night at the ballpark.",
    categories: ["creative", "social"],
    services_performed: ["Brand Film", "Content Production", "Social Media"],
    execution: "A two-minute brand film shot in 4K: on-camera interviews, event coverage and branded detail shots, finished with burned-in captions for sound-off viewing.",
    cover_image_url: "/media/photos/suite-sunset.jpg",
    hover_video_url: V("elevate"),
    gallery: ["/media/photos/epg-suite-bar.jpg", "/media/photos/epg-group-1.jpg", "/media/photos/epg-mascot.jpg", "/media/photos/suite-sunset.jpg", "/media/photos/epg-ballpark-portrait.jpg", "/media/photos/epg-group-2.jpg", "/media/photos/epg-suite-windows.jpg"],
    is_featured: true,
    sort_order: 10,
  }),
  work(2, {
    slug: "pet-grand-hotel",
    title: "Pet Grand Hotel",
    client_name: "Pet Grand Hotel",
    industry: "Hospitality",
    year: 2025,
    headline: "Five-star energy. Four-legged guests.",
    summary: "A promo film for a luxury pet hotel — the suites, the play areas and the guests themselves — made to feel like a real hotel tour.",
    categories: ["creative", "social"],
    services_performed: ["Promo Film", "Content Production"],
    execution: "Shot in 4K across suites, play yards and grooming rooms, with on-screen labels for each room type so the film doubles as a virtual tour.",
    cover_image_url: W("pet-grand-hotel-03"),
    hover_video_url: V("pet-grand-hotel"),
    gallery: [W("pet-grand-hotel-00"), W("pet-grand-hotel-03")],
    is_featured: true,
    sort_order: 20,
  }),
  work(3, {
    slug: "great-falls-estate",
    title: "Great Falls Estate",
    client_name: "Private listing",
    industry: "Luxury Real Estate",
    year: 2025,
    headline: "Selling the backyard before the front door.",
    summary: "A cinematic listing film for a Great Falls, Virginia estate — outdoor kitchen, pool house and grounds — shot horizontal for YouTube and the MLS, with a vertical cut for social.",
    categories: ["creative", "web"],
    services_performed: ["Listing Film", "Social Cut"],
    execution: "A gimbal-led walkthrough of the grounds and outdoor living spaces, finished in 4K, plus a separate vertical edit for Instagram.",
    cover_image_url: "/media/video/great-falls.jpg",
    hover_video_url: V("great-falls"),
    gallery: [W("great-falls-00"), W("great-falls-01"), W("great-falls-02"), W("great-falls-03")],
    city: "Great Falls",
    state: "VA",
    is_featured: false,
    sort_order: 30,
  }),
  work(4, {
    slug: "right-fit-summer-kick-off",
    title: "Summer Kick Off",
    client_name: "Right Fit Realty",
    industry: "Real Estate",
    year: 2025,
    headline: "The company cookout, captured as a brand story.",
    summary: "Event coverage for Right Fit Realty's Summer Kick Off — agents, families and partners on camera — edited into a recap film and short vertical highlights.",
    categories: ["social", "creative"],
    services_performed: ["Event Film", "Social Media", "Content Production"],
    execution: "Run-and-gun 4K coverage with quick on-camera interviews, sponsor moments and branded details, cut into a four-minute recap and vertical highlights.",
    cover_image_url: "/media/video/right-fit.jpg",
    hover_video_url: V("right-fit"),
    gallery: [W("right-fit-03")],
    is_featured: false,
    sort_order: 40,
  }),
  work(5, {
    slug: "smart-settlements",
    title: "Smart Settlements",
    client_name: "Smart Settlements",
    industry: "Real Estate Services",
    year: 2025,
    headline: "Putting faces to the closing table.",
    summary: "A brand video for a settlement team — the office, the people and the closing table — edited into a tight one-minute piece for social.",
    categories: ["creative", "social"],
    services_performed: ["Brand Video", "Content Production"],
    execution: "Walk-and-talk intros, meeting-room b-roll and team moments, shot in 4K and edited to just over a minute.",
    cover_image_url: W("smart-settlements-01"),
    hover_video_url: V("smart-settlements"),
    gallery: [W("smart-settlements-01"), W("smart-settlements-02"), W("smart-settlements-03")],
    is_featured: false,
    sort_order: 50,
  }),
  work(6, {
    slug: "2933-north-fairmont-street",
    title: "2933 N Fairmont Street",
    client_name: "Listing launch",
    industry: "Residential Real Estate",
    year: 2025,
    headline: "Just listed — and hard to scroll past.",
    summary: "Launch media for a five-bed, four-bath Falls Church home listed at $849,900: an agent-led listing film, HDR photography and a vertical reel for Instagram.",
    categories: ["creative", "social"],
    services_performed: ["Listing Film", "Photography", "Social Media"],
    execution: "An agent-on-camera walkthrough shot in 4K, HDR interiors for the MLS and a captioned reel posted with the listing announcement.",
    cover_image_url: W("fairmont-deck"),
    hover_video_url: V("fairmont"),
    gallery: [W("fairmont-living"), W("fairmont-01"), W("fairmont-lounge")],
    city: "Falls Church",
    state: "VA",
    is_featured: false,
    sort_order: 60,
  }),
  work(7, {
    slug: "17455-kagera-drive",
    title: "17455 Kagera Drive",
    client_name: "Lopez Realtors",
    industry: "Residential Real Estate",
    year: 2025,
    headline: "A listing film with a host.",
    summary: "Listing launch for Jenny Lopez of Lopez Realtors — an agent-hosted film, HDR photography and social cuts for the Just Listed push.",
    categories: ["creative", "social"],
    services_performed: ["Listing Film", "Photography", "Social Media"],
    execution: "An agent-hosted tour filmed in 4K, paired with a full HDR photo set and a vertical reel for Instagram.",
    cover_image_url: W("kagera-living"),
    hover_video_url: V("kagera"),
    gallery: [W("kagera-kitchen"), W("kagera-living")],
    is_featured: false,
    sort_order: 70,
  }),  work(8, {
    slug: "isaia",
    title: "Isaia",
    client_name: "Isaia",
    industry: "Fashion & Retail",
    year: 2025,
    headline: "Neapolitan tailoring, framed like a campaign.",
    summary: "Store photography and a vertical reel for Isaia's boutique — the storefront, the red-lacquered displays and the tailoring up close.",
    categories: ["creative", "social"],
    services_performed: ["Photography", "Reels", "Content Production"],
    execution: "A full boutique shoot — exteriors, wide interiors and product details — plus a 20-second reel cut for Instagram.",
    cover_image_url: W("isaia-store-1"),
    hover_video_url: V("isaia"),
    gallery: ["/media/photos/isaia-red-table.jpg", W("isaia-store-2"), "/media/photos/isaia-fitting.jpg", "/media/photos/isaia-entrance.jpg", W("isaia-store-3"), "/media/photos/isaia-styling.jpg", "/media/photos/isaia-shelves.jpg", W("isaia-store-4")],
    is_featured: true,
    sort_order: 5,
  }),
  work(9, {
    slug: "groom-guy",
    title: "Groom Guy",
    client_name: "Groom Guy",
    industry: "Men's Grooming",
    year: 2025,
    headline: "Fresh cuts. Sharper entrances.",
    summary: "A cinematic brand spot for Groom Guy — a sharply dressed crew owning a luxury lobby — shot in 4K for Instagram and Reels.",
    categories: ["creative", "social"],
    services_performed: ["Brand Film", "Social Media"],
    execution: "A choreographed walk-and-reveal through a luxury lobby, shot in 4K on a gimbal and graded for an editorial look.",
    cover_image_url: "/media/video/groom.jpg",
    hover_video_url: V("groom"),
    gallery: ["/media/photos/groom-team-2.jpg", "/media/photos/groom-portrait-1.jpg", "/media/photos/groom-handshake.jpg", "/media/photos/groom-portrait-2.jpg", "/media/photos/groom-chair.jpg", "/media/photos/groom-duo.jpg", "/media/photos/groom-team-1.jpg", "/media/photos/groom-portrait-3.jpg"],
    is_featured: true,
    sort_order: 15,
  }),
  work(10, {
    slug: "district-cup",
    title: "District Cup",
    client_name: null,
    industry: "Events & Sports",
    year: 2025,
    headline: "Polo, style and summer in the capital.",
    summary: "Event content from the District Cup polo match in D.C. — fast plays, sharp fits and the crowd between chukkers — cut into a vertical recap for Instagram.",
    categories: ["social", "creative"],
    services_performed: ["Event Coverage", "Reels"],
    execution: "Run-and-gun coverage on the field and in the tents, edited into a 27-second recap.",
    cover_image_url: W("polo-01"),
    hover_video_url: V("polo"),
    gallery: [W("polo-00"), W("polo-01")],
    is_featured: false,
    sort_order: 45,
  }),
  work(11, {
    slug: "tunlaw-penthouse",
    title: "Tunlaw Rd NW Penthouse",
    client_name: null,
    industry: "Luxury Real Estate",
    year: 2025,
    headline: "A penthouse with a skyline terrace, framed to match.",
    summary: "A cinematic listing film for a Washington, D.C. penthouse — the open living spaces and the rooftop terrace — cut in widescreen and vertical for the MLS and social.",
    categories: ["creative", "social"],
    services_performed: ["Listing Film", "Vertical Reel"],
    execution: "Gimbal-shot in 4K, graded for a bright, clean look, with a widescreen edit for the listing page and a vertical cut for Instagram.",
    cover_image_url: "/media/video/tunlaw-penthouse.jpg",
    hover_video_url: V("tunlaw-penthouse"),
    gallery: ["/media/photos/tunlaw-view.jpg", "/media/photos/tunlaw-living.jpg"],
    city: "Washington",
    state: "DC",
    is_featured: false,
    sort_order: 80,
  }),
  work(12, {
    slug: "8182-cobble-pond-way",
    title: "8182 Cobble Pond Way",
    client_name: "Listing launch",
    industry: "Residential Real Estate",
    year: 2025,
    headline: "A quiet Manassas home, made impossible to scroll past.",
    summary: "A walkthrough listing film for a beautifully maintained Manassas home, edited vertical-first for the Just Listed post.",
    categories: ["creative", "social"],
    services_performed: ["Listing Film", "Social Media"],
    execution: "A 4K gimbal walkthrough with on-screen captions, cut for Instagram and Reels.",
    cover_image_url: "/media/photos/cobble-twilight.jpg",
    hover_video_url: V("cobble-pond"),
    gallery: ["/media/photos/cobble-twilight.jpg", "/media/photos/cobble-dining.jpg", "/media/photos/cobble-living.jpg", "/media/photos/cobble-kitchen.jpg"],
    city: "Manassas",
    state: "VA",
    is_featured: false,
    sort_order: 90,
  }),
  work(13, {
    slug: "7906-garland-avenue",
    title: "7906 Garland Avenue",
    client_name: "Listing launch",
    industry: "Residential Real Estate",
    year: 2025,
    headline: "Classic character, thoughtfully filmed.",
    summary: "A Just Listed film for a charming home that blends classic character with thoughtful updates, presented by the listing agent and cut for Instagram.",
    categories: ["creative", "social"],
    services_performed: ["Listing Film", "Social Media"],
    execution: "An agent-presented 4K walkthrough, edited into a vertical film for the listing announcement.",
    cover_image_url: "/media/photos/garland-living.jpg",
    hover_video_url: V("garland"),
    gallery: ["/media/photos/garland-living.jpg", "/media/photos/garland-kitchen.jpg", "/media/photos/garland-bedroom.jpg"],
    is_featured: false,
    sort_order: 100,
  }),
  work(14, {
    slug: "10009-murnane-street",
    title: "10009 Murnane Street",
    client_name: "Listing launch",
    industry: "Residential Real Estate",
    year: 2025,
    headline: "Bright rooms, clean lines, a film that shows both.",
    summary: "A listing film that walks buyers through the home's main living spaces in soft natural light.",
    categories: ["creative"],
    services_performed: ["Listing Film"],
    execution: "A 4K gimbal walkthrough graded for a clean, bright look.",
    cover_image_url: "/media/video/murnane.jpg",
    hover_video_url: V("murnane"),
    gallery: ["/media/photos/murnane-exterior.jpg", "/media/photos/murnane-living.jpg", "/media/photos/murnane-kitchen.jpg", "/media/photos/murnane-dining.jpg"],
    is_featured: false,
    sort_order: 110,
  }),
  work(15, {
    slug: "9722-arnon-chapel-road",
    title: "9722 Arnon Chapel Road",
    client_name: "Listing launch",
    industry: "Luxury Real Estate",
    year: 2025,
    headline: "Great Falls, from the front door to the pool.",
    summary: "A listing film for a Great Falls, Virginia home, with a widescreen cut for the listing page and a vertical version for social.",
    categories: ["creative", "social"],
    services_performed: ["Listing Film", "Vertical Reel"],
    execution: "A 4K walkthrough shot on a gimbal and edited in two formats.",
    cover_image_url: "/media/photos/arnon-foyer.jpg",
    hover_video_url: V("arnon-chapel"),
    gallery: ["/media/photos/arnon-foyer.jpg", "/media/photos/arnon-billiards.jpg"],
    city: "Great Falls",
    state: "VA",
    is_featured: false,
    sort_order: 120,
  }),
  work(16, {
    slug: "224-stoic-street",
    title: "224 Stoic Street",
    client_name: "Listing launch",
    industry: "Residential Real Estate",
    year: 2025,
    headline: "The backyard pool gets its close-up.",
    summary: "A Loudoun County listing film that opens on the backyard and pool, then moves through the home.",
    categories: ["creative", "social"],
    services_performed: ["Listing Film", "Social Media"],
    execution: "A 4K gimbal walkthrough cut for Instagram, with the exterior as the hook.",
    cover_image_url: "/media/photos/chandelier-kitchen.jpg",
    hover_video_url: V("stoic-pool"),
    gallery: ["/media/photos/screened-porch.jpg", "/media/photos/chandelier-kitchen.jpg"],
    city: "Leesburg",
    state: "VA",
    is_featured: false,
    sort_order: 130,
  }),
  work(17, {
    slug: "right-fit-brewery-event",
    title: "Brewery Night at 2 Silos",
    client_name: "Right Fit Realty",
    industry: "Client Events",
    year: 2024,
    headline: "A client appreciation night, filmed like a festival.",
    summary: "Photo and video coverage of Right Fit Realty's client event at 2 Silos Brewery — the Yard, the taproom and the people — edited into a one-minute recap and a full-length film.",
    categories: ["creative", "social"],
    services_performed: ["Event Film", "Event Photography", "Social Media"],
    execution: "4K cinema-camera coverage and stills through golden hour, cut into a one-minute social recap and a longer horizontal film.",
    cover_image_url: "/media/photos/2-silos-stage.jpg",
    hover_video_url: V("silos-yard"),
    gallery: ["/media/photos/2-silos-taproom.jpg", "/media/photos/2-silos-garden.jpg", "/media/photos/right-fit-table.jpg", "/media/photos/2-silos-cider.jpg"],
    city: "Manassas",
    state: "VA",
    is_featured: true,
    sort_order: 25,
  }),
];

/** Businesses and professionals we've made work for — every name appears on the @jennings_media feed. */
export const REAL_CLIENTS: Client[] = [
  "Isaia",
  "Right Fit Realty",
  "The Inn at Little Washington",
  "Elevate Property Group",
  "The District Cup",
  "Groom Guy",
  "Pet Grand Hotel",
  "Smart Settlements",
  "Long & Foster",
  "CELSIUS",
  "POLOHUB",
  "ANIMA by GuiselleLove",
  "Keller Williams",
  "Perennial Real Estate",
  "Finn Family Group",
  "The Thompson Group",
  "Lopez Realtors",
  "Harmony Homes Experience",
  "Mark Middendorf",
  "Gali Sapir",
  "Lonnie Scales",
  "Russ Carter",
  "Briana Wansley",
  "Bill Hoffman",
  "Chris Jackson",
  "Sabina Gudauskas",
  "Uday Kammula",
  "Shawn Barsness",
  "HB Home Services",
  "DSDC Real Estate",
  "WAR Team",
  "Reynolds EmpowerHome Team",
].map((name, i) => ({
  id: `95000000-0000-4000-8000-${String(i + 1).padStart(12, "0")}`,
  name,
  logo_url: null,
  website_url: null,
  sort_order: (i + 1) * 10,
  is_published: true,
  is_sample: false,
}));

export type Reel = { slug: string; label: string; kind: string; href: string };

/** Vertical loops for the "made for the feed" wall (/public/media/video/<slug>.mp4 + .jpg). */
export const REELS: Reel[] = [
  { slug: "jennings-ad", label: BRAND.name, kind: "Agency spot", href: BRAND.instagram },
  { slug: "isaia", label: "Isaia", kind: "Menswear reel", href: "/work/isaia" },
  { slug: "epg-field", label: "Elevate Property Group", kind: "Event film", href: "/events" },
  { slug: "tunlaw-penthouse", label: "Tunlaw Rd NW Penthouse", kind: "Listing film", href: "/work/tunlaw-penthouse" },
  { slug: "elevate", label: "Elevate Property Group", kind: "Brand film", href: "/work/elevate-property-group" },
  { slug: "polo", label: "District Cup", kind: "Event recap", href: "/work/district-cup" },
  { slug: "pet-grand-hotel", label: "Pet Grand Hotel", kind: "Promo film", href: "/work/pet-grand-hotel" },
  { slug: "eh-chandelier", label: "Emerald Heights", kind: "Listing reel", href: "/real-estate#films" },
  { slug: "right-fit", label: "Right Fit Realty", kind: "Event recap", href: "/work/right-fit-summer-kick-off" },
  { slug: "fairmont", label: "2933 N Fairmont St", kind: "Listing reel", href: "/work/2933-north-fairmont-street" },
  { slug: "smart-settlements", label: "Smart Settlements", kind: "Brand video", href: "/work/smart-settlements" },
  { slug: "garland", label: "7906 Garland Ave", kind: "Listing film", href: "/work/7906-garland-avenue" },
  { slug: "cobble-pond", label: "8182 Cobble Pond Way", kind: "Listing film", href: "/work/8182-cobble-pond-way" },
  { slug: "kagera", label: "Lopez Realtors", kind: "Listing film", href: "/work/17455-kagera-drive" },
  { slug: "lake-shore", label: "1701 Lake Shore Crest", kind: "Listing reel", href: BRAND.instagram },
  { slug: "fall-festival", label: "Fall Festival", kind: "Event recap", href: BRAND.instagram },
  { slug: "sugarberry", label: "10465 Sugarberry", kind: "Listing film", href: BRAND.instagram },
];

/** Horizontal clips for the showreel preview montage. */
export const REEL_CLIPS = ["reel-1", "groom", "reel-2", "reel-3", "reel-4", "reel-5"].map((n) => ({ src: `/media/video/${n}.mp4`, poster: `/media/video/${n}.jpg` }));
export const SHOWREEL_FILM = "/media/video/film.mp4";
export const HERO_VIDEO = "/media/video/hero.mp4";

export type Frame = { src: string; video?: string; title: string; kind: string; shape: "wide" | "tall" };

/** "Shot by us" strip — only our own footage and photography. */
export const FRAMES: Frame[] = [
  { src: "/media/video/groom.jpg", video: "/media/video/groom.mp4", title: "Groom Guy", kind: "Brand film", shape: "wide" },
  { src: "/media/work/isaia-store-2.jpg", title: "Isaia", kind: "Retail photography", shape: "tall" },
  { src: "/media/video/reel-1.jpg", video: "/media/video/reel-1.mp4", title: "Waterfront home", kind: "Drone", shape: "wide" },
  { src: "/media/video/tunlaw-penthouse.jpg", video: "/media/video/tunlaw-penthouse.mp4", title: "Tunlaw Rd NW Penthouse", kind: "Listing film", shape: "tall" },
  { src: "/media/work/isaia-store-1.jpg", title: "Isaia storefront", kind: "Photography", shape: "wide" },
  { src: "/media/work/pet-grand-hotel-03.jpg", title: "Pet Grand Hotel", kind: "Brand film", shape: "tall" },
  { src: "/media/video/great-falls.jpg", video: "/media/video/great-falls.mp4", title: "Great Falls Estate", kind: "Listing film", shape: "wide" },
  { src: "/media/video/polo.jpg", video: "/media/video/polo.mp4", title: "District Cup", kind: "Event coverage", shape: "tall" },
  { src: "/media/work/fairmont-deck.jpg", title: "2933 N Fairmont St", kind: "Photography", shape: "wide" },
  { src: "/media/video/eh-chandelier.jpg", video: "/media/video/eh-chandelier.mp4", title: "Emerald Heights", kind: "Listing reel", shape: "tall" },
  { src: "/media/video/reel-5.jpg", video: "/media/video/reel-5.mp4", title: "Neighborhood reveal", kind: "Drone", shape: "wide" },
];

/** What each client is, for the Clients section. */
export const CLIENT_CATEGORY: Record<string, string> = {
  Isaia: "Menswear",
  "The Inn at Little Washington": "Hospitality",
  "Pet Grand Hotel": "Hospitality",
  "The District Cup": "Sports & events",
  POLOHUB: "Sports & events",
  "Groom Guy": "Grooming",
  CELSIUS: "Beverage",
  "ANIMA by GuiselleLove": "Fashion",
  "Right Fit Realty": "Brokerage",
  "Elevate Property Group": "Brokerage",
  "Smart Settlements": "Settlement services",
  "Long & Foster": "Brokerage",
  "Keller Williams": "Brokerage",
  "Perennial Real Estate": "Brokerage",
  "Finn Family Group": "Real estate team",
  "The Thompson Group": "Real estate team",
  "Lopez Realtors": "Real estate team",
  "Harmony Homes Experience": "Real estate team",
  "DSDC Real Estate": "Real estate",
  "WAR Team": "Real estate team",
  "Reynolds EmpowerHome Team": "Real estate team",
  "Mark Middendorf": "Realtor",
  "Gali Sapir": "Realtor",
  "Lonnie Scales": "Realtor",
  "Russ Carter": "Realtor",
  "Briana Wansley": "Realtor",
  "Bill Hoffman": "Realtor",
  "Chris Jackson": "Realtor",
  "Sabina Gudauskas": "Realtor",
  "Uday Kammula": "Realtor",
  "Shawn Barsness": "Mortgage lender",
  "HB Home Services": "Home services",
};
